# Generated by Django 2.2.1 on 2019-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(upload_to='images/')),
                ('family', models.ImageField(upload_to='images/')),
                ('kid', models.ImageField(upload_to='images/')),
                ('wedding', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
