# Generated by Django 2.2.1 on 2019-05-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='family',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='kid',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='wedding',
        ),
    ]
