# Generated by Django 2.2.1 on 2019-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190524_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='details',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
