# Generated by Django 2.2.1 on 2019-05-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20190524_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.ImageField(upload_to='lifestyle/')),
            ],
        ),
        migrations.RenameField(
            model_name='portrait_detail',
            old_name='port',
            new_name='portait_id',
        ),
        migrations.RenameField(
            model_name='portrait_detail',
            old_name='details',
            new_name='portrait_detail',
        ),
        migrations.CreateModel(
            name='Lifestyle_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle_detail', models.ImageField(upload_to='lifestyle/')),
                ('lifestyle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.Lifestyle')),
            ],
        ),
    ]
