# Generated by Django 2.2.1 on 2019-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20190527_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyle',
            name='lifestyle',
            field=models.ImageField(upload_to='lifestyles/'),
        ),
        migrations.AlterField(
            model_name='lifestyle_detail',
            name='lifestyle_detail',
            field=models.ImageField(upload_to='lifestyles/'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='portrait',
            field=models.ImageField(upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='portrait_detail',
            name='portrait_detail',
            field=models.ImageField(upload_to='portraits/'),
        ),
    ]
