# Generated by Django 2.2.1 on 2019-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20190531_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyle',
            name='lifestyle',
            field=models.ImageField(upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='lifestyle_detail',
            name='lifestyle_detail',
            field=models.ImageField(upload_to='portraits/'),
        ),
    ]
