# Generated by Django 2.2.1 on 2019-05-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20190531_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portrait_detail',
            name='portait_id',
        ),
        migrations.DeleteModel(
            name='Portrait',
        ),
        migrations.DeleteModel(
            name='Portrait_detail',
        ),
    ]
