# Generated by Django 2.2.1 on 2019-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20190531_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(upload_to='portraits/')),
            ],
        ),
        migrations.CreateModel(
            name='Portrait_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait_detail', models.ImageField(upload_to='portraits/')),
                ('portait_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.Portrait')),
            ],
        ),
    ]
