# Generated by Django 2.2.3 on 2019-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20190710_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='weddding',
            new_name='wedding',
        ),
    ]
